name: meinweg
description: Etappen-Tracking App für Wanderungen und Touren
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # GPS und Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # OpenStreetMap
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # Schrittzählung
  pedometer: ^3.0.0

  # Kamera und Bilder
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  file_picker: ^8.0.0+1
  image_gallery_saver: ^2.0.3

  # PDF und Audio
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^30.2.6
  open_file: ^3.3.2
  just_audio: ^0.9.36
  record: ^6.1.0

  # Datenbank und Speicher
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # Berechtigungen
  permission_handler: ^12.0.1

  # Verschlüsselung
  crypto: ^3.0.3

  # UI und Navigation
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  intl: ^0.20.2
  path: ^1.9.0
  confetti: ^0.7.0

  # HTTP Requests für Wetter-API
  http: ^1.1.0

  # CSV Parser für Impulsfragen
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Thumbnail_3 Minuten Atemraum.jpg
    - assets/images/Thumbnail_Atem Ruhe Freundlichkeit.jpg
    - assets/images/Thumbnail_Die_Magie_des_Pilgerns.jpg
    - assets/images/Thumbnail_Mache_dich_auf_den_Weg.jpg
    - assets/images/Thumbnail_Packliste.jpg
    - assets/images/Marco_Bach_2025.jpg
    - assets/audio/
    - assets/pdf/
    - icon.png
    - Zitate.csv
    - Impulsfragen.csv

  fonts:
    - family: MuseoSans
      fonts:
        - asset: assets/fonts/MuseoSans_100.otf
          weight: 100
        - asset: assets/fonts/MuseoSans_100_Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/MuseoSans_300.otf
          weight: 300
        - asset: assets/fonts/MuseoSans_300_Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/MuseoSans_500.otf
          weight: 500
        - asset: assets/fonts/MuseoSans_500_Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/MuseoSans_700.otf
          weight: 700
        - asset: assets/fonts/MuseoSans_700_Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/MuseoSans_900.otf
          weight: 900
        - asset: assets/fonts/MuseoSans_900_Italic.otf
          weight: 900
          style: italic
