name: meinweg
description: Etappen-Tracking App für Wanderungen und Touren
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # GPS und Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # Schrittzählung
  pedometer: ^3.0.0

  # Kamera und Bilder
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  file_picker: ^8.0.0+1

  # PDF und Audio
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^24.2.9
  open_file: ^3.3.2
  just_audio: ^0.9.36

  # Datenbank und Speicher
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2

  # Berechtigungen
  permission_handler: ^12.0.1

  # Verschlüsselung
  crypto: ^3.0.3

  # UI und Navigation
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  intl: ^0.18.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/pdf/
    - icon.png
